"""FastAPI-specific code generator implementation.

This module generates FastAPI + SQLAlchemy + Pydantic code from business DSL definitions.
"""
from datetime import datetime
from typing import Any, Dict, List, Optional

from app.business.dsl import (
    APIInterface,
    BusinessModel,
    EndpointDefinition,
    FieldDefinition,
    FieldType,
    HTTPMethod,
    ParameterLocation,
    RelationshipDefinition,
    RelationshipType,
)
from app.generation.base import (
    CodeGenerator,
    CodeGeneratorRegistry,
    GeneratedFile,
    GeneratedFileType,
    GenerationContext,
)


@CodeGeneratorRegistry.register("fastapi")
class FastAPIGenerator(CodeGenerator):
    """FastAPI-specific code generator.

    Generates:
    - SQLAlchemy models
    - Pydantic schemas
    - FastAPI routers
    - Repository classes
    - Service classes
    - Alembic migrations
    """

    def generate_model(self, model: BusinessModel) -> List[GeneratedFile]:
        """Generate SQLAlchemy model and Pydantic schemas."""
        files = []

        # Generate SQLAlchemy model
        files.append(self._generate_sqlalchemy_model(model))

        # Generate Pydantic schemas
        files.extend(self._generate_pydantic_schemas(model))

        return files

    def generate_api(
        self,
        api: APIInterface,
        model: Optional[BusinessModel] = None,
    ) -> List[GeneratedFile]:
        """Generate FastAPI router with endpoints."""
        return [self._generate_router(api, model)]

    def generate_repository(self, model: BusinessModel) -> List[GeneratedFile]:
        """Generate repository/data access layer."""
        return [self._generate_repository_class(model)]

    def generate_migration(
        self,
        model: BusinessModel,
        operation: str = "create",
        revision_id: Optional[str] = None,
    ) -> List[GeneratedFile]:
        """Generate Alembic migration file."""
        return [self._generate_alembic_migration(model, operation, revision_id)]

    def generate_service(self, model: BusinessModel) -> List[GeneratedFile]:
        """Generate service layer."""
        return [self._generate_service_class(model)]

    def generate_test(
        self,
        model: BusinessModel,
        test_type: str = "unit",
    ) -> List[GeneratedFile]:
        """Generate test files for a model."""
        files = []

        if test_type in ("unit", "all"):
            files.append(self._generate_unit_tests(model))

        if test_type in ("integration", "all"):
            files.append(self._generate_integration_tests(model))

        return files

    # -----------------------------------------------------------------------
    # SQLAlchemy Model Generation
    # -----------------------------------------------------------------------

    def _generate_sqlalchemy_model(self, model: BusinessModel) -> GeneratedFile:
        """Generate SQLAlchemy model file."""
        imports = self._get_model_imports(model)
        fields_code = self._generate_model_fields(model)
        relationships_code = self._generate_model_relationships(model)
        methods_code = self._generate_model_methods(model)

        content = f'''"""SQLAlchemy model for {model.name}.

Generated by AFSA Code Generator.
"""
from datetime import datetime
from typing import Optional
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    Integer,
    String,
    Text,
    Float,
    Numeric,
    JSON,
    LargeBinary,
    Index,
    ForeignKey,
)
from sqlalchemy.dialects.postgresql import UUID, ARRAY
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.database import Base


class {model.name}(Base):
    """SQLAlchemy model for {model.name}.

    {model.description}
    """

    __tablename__ = "{model.table_name}"
{fields_code}
{relationships_code}
{methods_code}
'''

        return GeneratedFile(
            file_type=GeneratedFileType.MODEL,
            file_name=f"{model.table_name}.py",
            file_path=f"app/models/{model.table_name}.py",
            content=content,
            dependencies=["sqlalchemy>=2.0.0"],
            imports=imports,
        )

    def _get_model_imports(self, model: BusinessModel) -> List[str]:
        """Get imports needed for the model."""
        imports = [
            "from datetime import datetime",
            "from typing import Optional",
            "from sqlalchemy import Boolean, DateTime, Integer, String, Text",
            "from sqlalchemy.orm import Mapped, mapped_column, relationship",
            "from app.infrastructure.database import Base",
        ]

        # Check for UUID fields
        for field in model.fields:
            if field.field_type == FieldType.UUID:
                imports.append("from uuid import uuid4")
                imports.append("from sqlalchemy.dialects.postgresql import UUID")
                break

        return imports

    def _generate_model_fields(self, model: BusinessModel) -> str:
        """Generate SQLAlchemy field definitions."""
        fields_code = []

        for field in model.fields:
            field_code = self._generate_single_field(field)
            fields_code.append(f"    {field_code}")

        # Add indexes
        if model.indexes:
            fields_code.append("")
            fields_code.append("    __table_args__ = (")
            for idx in model.indexes:
                idx_fields = ", ".join(f'"{f}"' for f in idx.fields)
                unique_str = ", unique=True" if idx.unique else ""
                fields_code.append(
                    f'        Index("{idx.name}", {idx_fields}{unique_str}),'
                )
            fields_code.append("    )")

        return "\n".join(fields_code)

    def _generate_single_field(self, field: FieldDefinition) -> str:
        """Generate a single SQLAlchemy field definition."""
        col_type = self._get_sqlalchemy_type(field)

        args = []

        # Primary key
        if field.primary_key:
            args.append("primary_key=True")

        # Nullable
        if field.nullable or not field.required:
            args.append("nullable=True")
        else:
            args.append("nullable=False")

        # Unique
        if field.unique:
            args.append("unique=True")

        # Default
        if field.default is not None:
            if isinstance(field.default, str):
                args.append(f'default="{field.default}"')
            elif isinstance(field.default, bool):
                args.append(f"default={field.default}")
            else:
                args.append(f"default={field.default}")

        # Index
        if field.index and not field.primary_key:
            args.append("index=True")

        # Foreign key
        if field.foreign_key:
            args.append(f'ForeignKey("{field.foreign_key}")')

        args_str = ", ".join(args) if args else ""

        return f'{field.name}: Mapped[{col_type}] = mapped_column({args_str})'

    def _get_sqlalchemy_type(self, field: FieldDefinition) -> str:
        """Get SQLAlchemy type for a field."""
        type_map = {
            FieldType.STRING: "String",
            FieldType.INTEGER: "Integer",
            FieldType.FLOAT: "Float",
            FieldType.BOOLEAN: "Boolean",
            FieldType.DATETIME: "DateTime",
            FieldType.DATE: "Date",
            FieldType.TIME: "Time",
            FieldType.UUID: "UUID",
            FieldType.JSON: "JSON",
            FieldType.BINARY: "LargeBinary",
            FieldType.TEXT: "Text",
            FieldType.DECIMAL: "Numeric",
            FieldType.EMAIL: "String",
            FieldType.URL: "String",
            FieldType.PHONE: "String",
        }

        base_type = type_map.get(field.field_type, "String")

        # Add length for String types
        if base_type == "String" and field.field_type in (
            FieldType.STRING,
            FieldType.EMAIL,
            FieldType.URL,
            FieldType.PHONE,
        ):
            max_len = 255
            for v in field.validations:
                if v.rule_type == "max_length":
                    max_len = v.value
                    break
            return f"{base_type}({max_len})"

        return base_type

    def _generate_model_relationships(self, model: BusinessModel) -> str:
        """Generate SQLAlchemy relationship definitions."""
        if not model.relationships:
            return ""

        relationships = ["", "    # Relationships"]

        for rel in model.relationships:
            rel_code = self._generate_single_relationship(rel)
            relationships.append(f"    {rel_code}")

        return "\n".join(relationships)

    def _generate_single_relationship(self, rel: RelationshipDefinition) -> str:
        """Generate a single SQLAlchemy relationship definition."""
        args = [f'"{rel.target_model}"']

        if rel.back_populates:
            args.append(f'back_populates="{rel.back_populates}"')

        if rel.cascade:
            args.append(f'cascade="{rel.cascade}"')

        if rel.lazy:
            args.append(f'lazy="{rel.lazy}"')

        args_str = ", ".join(args)

        return f"{rel.name}: Mapped[{rel.target_model}] = relationship({args_str})"

    def _generate_model_methods(self, model: BusinessModel) -> str:
        """Generate model methods (to_dict, etc.)."""
        pk = model.get_primary_key()
        pk_name = pk.name if pk else "id"

        return f'''
    def to_dict(self) -> dict:
        """Convert model to dictionary."""
        return {{
            "{pk_name}": self.{pk_name},
            # Add other fields as needed
        }}

    def __repr__(self) -> str:
        return f"<{model.name}({pk_name}={{self.{pk_name}}})>"
'''

    # -----------------------------------------------------------------------
    # Pydantic Schema Generation
    # -----------------------------------------------------------------------

    def _generate_pydantic_schemas(self, model: BusinessModel) -> List[GeneratedFile]:
        """Generate Pydantic schema files."""
        files = []

        # All schemas are generated in a single file for convenience
        files.append(self._generate_base_schema(model))

        return files

    def _generate_base_schema(self, model: BusinessModel) -> GeneratedFile:
        """Generate base Pydantic schema."""
        fields_code = self._generate_schema_fields(model)

        content = f'''"""Pydantic schemas for {model.name}.

Generated by AFSA Code Generator.
"""
from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, field_validator


class {model.name}Base(BaseModel):
    """Base schema for {model.name}."""

{fields_code}


class {model.name}Create({model.name}Base):
    """Schema for creating {model.name}."""

    pass


class {model.name}Update(BaseModel):
    """Schema for updating {model.name}."""

{fields_code}


class {model.name}Response({model.name}Base):
    """Response schema for {model.name}."""

    id: int = Field(..., description="Unique identifier")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")

    class Config:
        from_attributes = True


class {model.name}ListResponse(BaseModel):
    """List response schema for {model.name}."""

    items: List[{model.name}Response]
    total: int
    page: int
    page_size: int
'''

        return GeneratedFile(
            file_type=GeneratedFileType.SCHEMA,
            file_name=f"{model.table_name}_schemas.py",
            file_path=f"app/schemas/{model.table_name}_schemas.py",
            content=content,
            dependencies=["pydantic>=2.0.0"],
        )

    def _generate_schema_fields(self, model: BusinessModel) -> str:
        """Generate Pydantic field definitions."""
        fields = []

        for field in model.fields:
            if field.primary_key or field.name in (
                "created_at",
                "updated_at",
                "deleted_at",
            ):
                continue

            field_code = self._generate_single_schema_field(field)
            fields.append(f"    {field_code}")

        if not fields:
            fields.append("    pass")

        return "\n".join(fields)

    def _generate_single_schema_field(self, field: FieldDefinition) -> str:
        """Generate a single Pydantic field definition."""
        pydantic_type = self._get_pydantic_type(field)

        args = []

        if field.description:
            args.append(f'description="{field.description}"')

        if field.default is not None:
            args.append(f"default={repr(field.default)}")
        elif not field.required or field.nullable:
            args.append("default=None")
            pydantic_type = f"Optional[{pydantic_type}]"

        args_str = ", ".join(args)

        if args_str:
            return f"{field.name}: {pydantic_type} = Field({args_str})"
        elif not field.required or field.nullable:
            return f"{field.name}: {pydantic_type} = None"
        else:
            return f"{field.name}: {pydantic_type}"

    def _get_pydantic_type(self, field: FieldDefinition) -> str:
        """Get Pydantic type for a field."""
        type_map = {
            FieldType.STRING: "str",
            FieldType.INTEGER: "int",
            FieldType.FLOAT: "float",
            FieldType.BOOLEAN: "bool",
            FieldType.DATETIME: "datetime",
            FieldType.DATE: "date",
            FieldType.TIME: "time",
            FieldType.UUID: "UUID",
            FieldType.JSON: "dict",
            FieldType.BINARY: "bytes",
            FieldType.TEXT: "str",
            FieldType.DECIMAL: "Decimal",
            FieldType.EMAIL: "str",
            FieldType.URL: "str",
            FieldType.PHONE: "str",
        }

        return type_map.get(field.field_type, "str")

    # -----------------------------------------------------------------------
    # Router Generation
    # -----------------------------------------------------------------------

    def _generate_router(
        self,
        api: APIInterface,
        model: Optional[BusinessModel],
    ) -> GeneratedFile:
        """Generate FastAPI router file."""
        endpoints_code = self._generate_endpoints(api, model)

        content = f'''"""FastAPI router for {api.name}.

Generated by AFSA Code Generator.
"""
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.infrastructure.database import get_db
# Import schemas when available

router = APIRouter(
    prefix="{api.base_path}",
    tags={api.tags},
)

{endpoints_code}
'''

        return GeneratedFile(
            file_type=GeneratedFileType.ROUTER,
            file_name=f"{api.name.lower()}_router.py",
            file_path=f"app/api/routers/{api.name.lower()}_router.py",
            content=content,
            dependencies=["fastapi>=0.100.0"],
        )

    def _generate_endpoints(
        self,
        api: APIInterface,
        model: Optional[BusinessModel],
    ) -> str:
        """Generate endpoint functions."""
        endpoints = []

        for endpoint in api.endpoints:
            endpoint_code = self._generate_single_endpoint(endpoint, model)
            endpoints.append(endpoint_code)

        return "\n\n".join(endpoints)

    def _generate_single_endpoint(
        self,
        endpoint: EndpointDefinition,
        model: Optional[BusinessModel],
    ) -> str:
        """Generate a single endpoint function."""
        # Get HTTP method decorator
        method_map = {
            HTTPMethod.GET: "get",
            HTTPMethod.POST: "post",
            HTTPMethod.PUT: "put",
            HTTPMethod.PATCH: "patch",
            HTTPMethod.DELETE: "delete",
        }

        method_name = method_map.get(endpoint.method, "get")

        # Build path parameters
        path_params = []
        for param in endpoint.parameters:
            if param.location == ParameterLocation.PATH:
                path_params.append(f"{param.name}: {param.param_type}")

        # Build query parameters
        query_params = []
        for param in endpoint.parameters:
            if param.location == ParameterLocation.QUERY:
                default = param.default if param.default is not None else "..."
                query_params.append(
                    f"{param.name}: {param.param_type} = Query({default})"
                )

        # Build function signature
        all_params = ["db: Session = Depends(get_db)"]
        all_params.extend(path_params)
        all_params.extend(query_params)

        params_str = ", ".join(all_params)

        # Build docstring
        docstring = f'"""{endpoint.summary}.\n\n{endpoint.description}\n"""'

        return f'''@router.{method_name}(
    "{endpoint.path}",
    status_code=status.HTTP_200_OK,
    summary="{endpoint.summary}",
)
async def {endpoint.name}(
    {params_str}
) -> dict:
    {docstring}
    # TODO: Implement endpoint logic
    return {{"message": "Not implemented"}}
'''

    # -----------------------------------------------------------------------
    # Repository Generation
    # -----------------------------------------------------------------------

    def _generate_repository_class(self, model: BusinessModel) -> GeneratedFile:
        """Generate repository class."""
        model_name = model.name
        model_var = model_name.lower()
        table_name = model.table_name

        content = f'''"""Repository for {model_name}.

Generated by AFSA Code Generator.
"""
from typing import List, Optional, Any
from sqlalchemy.orm import Session
from sqlalchemy import and_, or_

from app.models.{table_name} import {model_name}


class {model_name}Repository:
    """Repository for {model_name} operations."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: dict) -> {model_name}:
        """Create a new {model_name}."""
        {model_var} = {model_name}(**data)
        self.db.add({model_var})
        self.db.commit()
        self.db.refresh({model_var})
        return {model_var}

    def get_by_id(self, id: int) -> Optional[{model_name}]:
        """Get {model_name} by ID."""
        return self.db.query({model_name}).filter({model_name}.id == id).first()

    def get_all(
        self,
        skip: int = 0,
        limit: int = 100,
        filters: Optional[dict] = None,
    ) -> List[{model_name}]:
        """Get all {model_name} instances with optional filtering."""
        query = self.db.query({model_name})

        if filters:
            for key, value in filters.items():
                if hasattr({model_name}, key):
                    query = query.filter(getattr({model_name}, key) == value)

        return query.offset(skip).limit(limit).all()

    def update(self, id: int, data: dict) -> Optional[{model_name}]:
        """Update a {model_name}."""
        {model_var} = self.get_by_id(id)
        if not {model_var}:
            return None

        for key, value in data.items():
            if hasattr({model_var}, key):
                setattr({model_var}, key, value)

        self.db.commit()
        self.db.refresh({model_var})
        return {model_var}

    def delete(self, id: int) -> bool:
        """Delete a {model_name}."""
        {model_var} = self.get_by_id(id)
        if not {model_var}:
            return False

        self.db.delete({model_var})
        self.db.commit()
        return True

    def count(self, filters: Optional[dict] = None) -> int:
        """Count {model_name} instances."""
        query = self.db.query({model_name})

        if filters:
            for key, value in filters.items():
                if hasattr({model_name}, key):
                    query = query.filter(getattr({model_name}, key) == value)

        return query.count()
'''

        return GeneratedFile(
            file_type=GeneratedFileType.REPOSITORY,
            file_name=f"{table_name}_repository.py",
            file_path=f"app/repositories/{table_name}_repository.py",
            content=content,
            dependencies=["sqlalchemy>=2.0.0"],
        )

    # -----------------------------------------------------------------------
    # Service Generation
    # -----------------------------------------------------------------------

    def _generate_service_class(self, model: BusinessModel) -> GeneratedFile:
        """Generate service class."""
        model_name = model.name
        model_var = model_name.lower()
        table_name = model.table_name

        content = f'''"""Service layer for {model_name}.

Generated by AFSA Code Generator.
"""
from typing import List, Optional
from sqlalchemy.orm import Session

from app.repositories.{table_name}_repository import {model_name}Repository
# Import schemas when available


class {model_name}Service:
    """Service for {model_name} business logic."""

    def __init__(self, db: Session):
        self.repository = {model_name}Repository(db)

    def create(self, data: dict) -> dict:
        """Create a new {model_name}.

        Args:
            data: {model_name} creation data

        Returns:
            Created {model_name}
        """
        # TODO: Add business validation logic
        {model_var} = self.repository.create(data)
        return {model_var}.to_dict()

    def get_by_id(self, id: int) -> Optional[dict]:
        """Get {model_name} by ID.

        Args:
            id: {model_name} ID

        Returns:
            {model_name} if found, None otherwise
        """
        {model_var} = self.repository.get_by_id(id)
        return {model_var}.to_dict() if {model_var} else None

    def get_list(
        self,
        page: int = 1,
        page_size: int = 20,
        filters: Optional[dict] = None,
    ) -> dict:
        """Get paginated list of {model_name}.

        Args:
            page: Page number
            page_size: Items per page
            filters: Optional filters

        Returns:
            Paginated {model_name} list
        """
        skip = (page - 1) * page_size
        items = self.repository.get_all(skip=skip, limit=page_size, filters=filters)
        total = self.repository.count(filters=filters)

        return {{
            "items": [item.to_dict() for item in items],
            "total": total,
            "page": page,
            "page_size": page_size,
        }}

    def update(self, id: int, data: dict) -> Optional[dict]:
        """Update a {model_name}.

        Args:
            id: {model_name} ID
            data: Update data

        Returns:
            Updated {model_name} if found, None otherwise
        """
        # TODO: Add business validation logic
        {model_var} = self.repository.update(id, data)
        return {model_var}.to_dict() if {model_var} else None

    def delete(self, id: int) -> bool:
        """Delete a {model_name}.

        Args:
            id: {model_name} ID

        Returns:
            True if deleted, False if not found
        """
        return self.repository.delete(id)
'''

        return GeneratedFile(
            file_type=GeneratedFileType.SERVICE,
            file_name=f"{table_name}_service.py",
            file_path=f"app/services/{table_name}_service.py",
            content=content,
            dependencies=["sqlalchemy>=2.0.0"],
        )

    # -----------------------------------------------------------------------
    # Migration Generation
    # -----------------------------------------------------------------------

    def _generate_alembic_migration(
        self,
        model: BusinessModel,
        operation: str,
        revision_id: Optional[str],
    ) -> GeneratedFile:
        """Generate Alembic migration file."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        revision = revision_id or timestamp

        if operation == "create":
            upgrade_code = self._generate_migration_create(model)
            downgrade_code = self._generate_migration_drop(model)
        elif operation == "drop":
            upgrade_code = self._generate_migration_drop(model)
            downgrade_code = self._generate_migration_create(model)
        else:
            upgrade_code = "# TODO: Implement alter migration"
            downgrade_code = "# TODO: Implement alter migration reversal"

        content = f'''"""{operation.capitalize()} {model.name} table.

Revision ID: {revision}
Revises:
Create Date: {datetime.now().isoformat()}

Generated by AFSA Code Generator.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "{revision}"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
{upgrade_code}


def downgrade() -> None:
    """Downgrade database schema."""
{downgrade_code}
'''

        return GeneratedFile(
            file_type=GeneratedFileType.MIGRATION,
            file_name=f"{revision}_{operation}_{model.table_name}.py",
            file_path=f"alembic/versions/{revision}_{operation}_{model.table_name}.py",
            content=content,
            dependencies=["alembic>=1.12.0", "sqlalchemy>=2.0.0"],
        )

    def _generate_migration_create(self, model: BusinessModel) -> str:
        """Generate create table migration."""
        columns = []

        for field in model.fields:
            col_def = self._generate_migration_column(field)
            columns.append(f"        {col_def}")

        columns_str = ",\n".join(columns)

        return f'''    op.create_table(
        "{model.table_name}",
{columns_str},
    )'''

    def _generate_migration_column(self, field: FieldDefinition) -> str:
        """Generate a migration column definition."""
        col_type = self._get_alembic_type(field)

        args = [f'sa.{col_type}']

        if field.primary_key:
            args.append("primary_key=True")

        if field.nullable or not field.required:
            args.append("nullable=True")
        else:
            args.append("nullable=False")

        if field.auto_increment:
            args.append("autoincrement=True")

        if field.unique:
            args.append("unique=True")

        args_str = ", ".join(args)

        return f'sa.Column("{field.name}", {args_str})'

    def _get_alembic_type(self, field: FieldDefinition) -> str:
        """Get Alembic/SQLAlchemy type for migration."""
        type_map = {
            FieldType.STRING: "String(255)",
            FieldType.INTEGER: "Integer()",
            FieldType.FLOAT: "Float()",
            FieldType.BOOLEAN: "Boolean()",
            FieldType.DATETIME: "DateTime(timezone=True)",
            FieldType.DATE: "Date()",
            FieldType.TIME: "Time()",
            FieldType.UUID: "postgresql.UUID(as_uuid=True)",
            FieldType.JSON: "JSON()",
            FieldType.BINARY: "LargeBinary()",
            FieldType.TEXT: "Text()",
            FieldType.DECIMAL: "Numeric(precision=10, scale=2)",
            FieldType.EMAIL: "String(255)",
            FieldType.URL: "String(500)",
            FieldType.PHONE: "String(20)",
        }

        return type_map.get(field.field_type, "String(255)")

    def _generate_migration_drop(self, model: BusinessModel) -> str:
        """Generate drop table migration."""
        return f'    op.drop_table("{model.table_name}")'

    # -----------------------------------------------------------------------
    # Test Generation
    # -----------------------------------------------------------------------

    def _generate_unit_tests(self, model: BusinessModel) -> GeneratedFile:
        """Generate unit test file."""
        model_name = model.name
        table_name = model.table_name

        content = f'''"""Unit tests for {model_name}.

Generated by AFSA Code Generator.
"""
import pytest
from unittest.mock import Mock, patch, MagicMock

from app.services.{table_name}_service import {model_name}Service
from app.repositories.{table_name}_repository import {model_name}Repository


class Test{model_name}Service:
    """Tests for {model_name}Service."""

    @pytest.fixture
    def mock_db(self):
        """Create mock database session."""
        return MagicMock()

    @pytest.fixture
    def service(self, mock_db):
        """Create service instance."""
        return {model_name}Service(mock_db)

    def test_create(self, service):
        """Test creating a {model_name}."""
        data = {{"name": "Test"}}
        with patch.object(service.repository, "create") as mock_create:
            mock_model = Mock()
            mock_model.to_dict.return_value = {{"id": 1, "name": "Test"}}
            mock_create.return_value = mock_model

            result = service.create(data)

            mock_create.assert_called_once_with(data)
            assert result["name"] == "Test"

    def test_get_by_id(self, service):
        """Test getting a {model_name} by ID."""
        with patch.object(service.repository, "get_by_id") as mock_get:
            mock_model = Mock()
            mock_model.to_dict.return_value = {{"id": 1, "name": "Test"}}
            mock_get.return_value = mock_model

            result = service.get_by_id(1)

            mock_get.assert_called_once_with(1)
            assert result["id"] == 1

    def test_get_by_id_not_found(self, service):
        """Test getting a non-existent {model_name}."""
        with patch.object(service.repository, "get_by_id") as mock_get:
            mock_get.return_value = None

            result = service.get_by_id(999)

            assert result is None

    def test_delete(self, service):
        """Test deleting a {model_name}."""
        with patch.object(service.repository, "delete") as mock_delete:
            mock_delete.return_value = True

            result = service.delete(1)

            mock_delete.assert_called_once_with(1)
            assert result is True


class Test{model_name}Repository:
    """Tests for {model_name}Repository."""

    @pytest.fixture
    def mock_db(self):
        """Create mock database session."""
        return MagicMock()

    @pytest.fixture
    def repository(self, mock_db):
        """Create repository instance."""
        return {model_name}Repository(mock_db)

    def test_create(self, repository, mock_db):
        """Test creating a {model_name}."""
        # TODO: Implement test
        pass

    def test_get_by_id(self, repository, mock_db):
        """Test getting a {model_name} by ID."""
        # TODO: Implement test
        pass
'''

        return GeneratedFile(
            file_type=GeneratedFileType.TEST,
            file_name=f"test_{table_name}.py",
            file_path=f"tests/unit/test_{table_name}.py",
            content=content,
            dependencies=["pytest>=7.0.0"],
        )

    def _generate_integration_tests(self, model: BusinessModel) -> GeneratedFile:
        """Generate integration test file."""
        model_name = model.name
        table_name = model.table_name

        content = f'''"""Integration tests for {model_name}.

Generated by AFSA Code Generator.
"""
import pytest
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

# Import your app and models when available


@pytest.fixture
def client():
    """Create test client."""
    # TODO: Configure test client
    pass


class Test{model_name}API:
    """Integration tests for {model_name} API."""

    def test_list_{table_name}(self, client):
        """Test listing {table_name}."""
        # TODO: Implement test
        pass

    def test_create_{table_name}(self, client):
        """Test creating a {model_name}."""
        # TODO: Implement test
        pass

    def test_get_{table_name}(self, client):
        """Test getting a {model_name} by ID."""
        # TODO: Implement test
        pass

    def test_update_{table_name}(self, client):
        """Test updating a {model_name}."""
        # TODO: Implement test
        pass

    def test_delete_{table_name}(self, client):
        """Test deleting a {model_name}."""
        # TODO: Implement test
        pass
'''

        return GeneratedFile(
            file_type=GeneratedFileType.TEST,
            file_name=f"test_{table_name}_integration.py",
            file_path=f"tests/integration/test_{table_name}_integration.py",
            content=content,
            dependencies=["pytest>=7.0.0", "httpx>=0.24.0"],
        )